version: "3.8"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"

  redis:
    image: redis
    restart: always
    ports:
      - "${REDIS_PORT}:6379"

  backend:
    build: .
    restart: always
    depends_on:
      - db
      - redis
    ports:
      - "${APP_PORT}:8000"
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  worker:
    build: .
    restart: always
    depends_on:
      - backend
      - redis
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    command: celery -A worker.celery_config worker --loglevel=info
