apiVersion: v1
kind: Service
metadata:
  name: worker-service
  namespace: metascraper
spec:
  selector:
    app: celery-worker
  ports:
    - protocol: TCP
      port: 5555
      targetPort: 5555
  type: ClusterIP
